In [15]:
import pandas as pd 
import numpy as np 

In [16]:

dataset = pd.read_csv("Salary_Data.csv")

In [18]:

dataset.shape


(6704, 6)

In [19]:

dataset.head(10)

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
5,29.0,Male,Bachelor's,Marketing Analyst,2.0,55000.0
6,42.0,Female,Master's,Product Manager,12.0,120000.0
7,31.0,Male,Bachelor's,Sales Manager,4.0,80000.0
8,26.0,Female,Bachelor's,Marketing Coordinator,1.0,45000.0
9,38.0,Male,PhD,Senior Scientist,10.0,110000.0


In [20]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6704 entries, 0 to 6703
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Age                  6702 non-null   float64
 1   Gender               6702 non-null   object 
 2   Education Level      6701 non-null   object 
 3   Job Title            6702 non-null   object 
 4   Years of Experience  6701 non-null   float64
 5   Salary               6699 non-null   float64
dtypes: float64(3), object(3)
memory usage: 235.8+ KB


In [22]:

dataset.isna()


,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
...,...,...,...,...,...,...
6699,False,False,False,False,False,False
6700,False,False,False,False,False,False
6701,False,False,False,False,False,False
6702,False,False,False,False,False,False


In [23]:
dataset.duplicated().sum()

4912

In [24]:

dataset.drop_duplicates(keep ="first", inplace= True)

In [25]:
dataset.duplicated().sum()

0

In [26]:
dataset.shape 

(1792, 6)

In [27]:
dataset.isna().sum()

Age                    1
Gender                 1
Education Level        2
Job Title              1
Years of Experience    2
Salary                 4
dtype: int64

In [28]:
dataset['Age'].unique()

array([32., 28., 45., 36., 52., 29., 42., 31., 26., 38., 48., 35., 40.,
       27., 44., 33., 39., 25., 51., 34., 47., 30., 41., 37., 24., 43.,
       50., 46., 49., 23., 53., nan, 61., 57., 62., 55., 56., 54., 60.,
       58., 22., 21.])

In [29]:

Occupation_mode = dataset.Age.mode()[0]
print(Occupation_mode)

29.0


In [30]:
dataset.Age.fillna(Occupation_mode, inplace=True)

In [31]:
Salary_mode = dataset.Salary.mode()[0]
print(Salary_mode)

120000.0


In [32]:
dataset.Salary.fillna(Salary_mode, inplace=True)

In [33]:
dataset['Salary'].unique()

array([ 90000.,  65000., 150000.,  60000., 200000.,  55000., 120000.,
        80000.,  45000., 110000.,  75000., 140000., 130000.,  40000.,
       125000., 115000.,  35000., 180000., 190000.,  50000., 250000.,
       170000., 160000.,  85000.,  95000., 105000.,  70000., 100000.,
        30000., 135000., 220000., 175000., 185000., 145000., 155000.,
          350., 195000., 198000., 196000., 193000.,  92000., 165000.,
       162000., 197000., 142000., 182000., 210000.,    550., 122485.,
       169159., 187081., 166109.,  78354.,  90249., 132720., 161568.,
       127346., 120177.,  69032., 101332., 121450., 166375., 185119.,
       149217., 166512., 186963.,  75072., 163398., 103947., 179180.,
       175966., 190004., 152039.,  76742., 191790., 139398.,  95845.,
       160976., 126753., 161393., 139817., 181714., 114776., 105725.,
        52731., 106492.,  73895., 119836.,  99747., 168287., 115920.,
       128078.,  51265., 165919., 188651.,  55538., 193964., 104702.,
       172955., 1380

In [50]:
dataset['Salary'] = dataset['Salary'].astype(str).str.replace("k", "000")

In [51]:
dataset['Salary'] = dataset['Salary'].astype(str).str.replace("usd","")

In [52]:
dataset['Salary'] = dataset['Salary'].astype(str).str.replace("USD","")

In [53]:
dataset['Salary'] = dataset['Salary'].replace("USD","")

In [54]:
dataset['Salary'] = dataset['Salary'].replace("$","")

In [55]:
dataset['Salary'].unique()

array(['90000.0', '65000.0', '150000.0', '60000.0', '200000.0', '55000.0',
       '120000.0', '80000.0', '45000.0', '110000.0', '75000.0',
       '140000.0', '130000.0', '40000.0', '125000.0', '115000.0',
       '35000.0', '180000.0', '190000.0', '50000.0', '250000.0',
       '170000.0', '160000.0', '85000.0', '95000.0', '105000.0',
       '70000.0', '100000.0', '30000.0', '135000.0', '220000.0',
       '175000.0', '185000.0', '145000.0', '155000.0', '350.0',
       '195000.0', '198000.0', '196000.0', '193000.0', '92000.0',
       '165000.0', '162000.0', '197000.0', '142000.0', '182000.0',
       '210000.0', '550.0', '122485.0', '169159.0', '187081.0',
       '166109.0', '78354.0', '90249.0', '132720.0', '161568.0',
       '127346.0', '120177.0', '69032.0', '101332.0', '121450.0',
       '166375.0', '185119.0', '149217.0', '166512.0', '186963.0',
       '75072.0', '163398.0', '103947.0', '179180.0', '175966.0',
       '190004.0', '152039.0', '76742.0', '191790.0', '139398.0',
       '9

In [61]:
YearsOfExperience_median = dataset['Years of Experience'].median()
print(YearsOfExperience_median)

8.0


In [62]:
dataset['Years of Experience'].fillna(dataset['Years of Experience'].median(), inplace=True)

In [63]:
dataset['Years of Experience'].fillna(dataset['Years of Experience'].median(), inplace=True)


In [64]:
dataset['Years of Experience'].unique()

array([ 5. ,  3. , 15. ,  7. , 20. ,  2. , 12. ,  4. ,  1. , 10. , 18. ,
        6. , 14. , 16. ,  0. , 22. , 19. ,  9. , 13. , 11. , 25. , 21. ,
        8. , 17. , 23. , 24. ,  0.5,  1.5, 31. , 30. , 28. , 33. , 27. ,
       34. , 29. , 26. , 32. ])

In [65]:
YearsOfExperience_mode = dataset['Years of Experience'].mode()[0]
print(YearsOfExperience_mode)


2.0


In [66]:
dataset['Years of Experience'].fillna(dataset['Years of Experience'].mode()[0], inplace=True)


In [70]:
dataset['Years of Experience'].unique()

array(['5.0', '3.0', '15.0', '7.0', '20.0', '2.0', '12.0', '4.0', '1.0',
       '10.0', '18.0', '6.0', '14.0', '16.0', '0.0', '22.0', '19.0',
       '9.0', '13.0', '11.0', '25.0', '21.0', '8.0', '17.0', '23.0',
       '24.0', '0.5', '1.5', '31.0', '30.0', '28.0', '33.0', '27.0',
       '34.0', '29.0', '26.0', '32.0'], dtype=object)

In [69]:
dataset['Years of Experience'] = dataset['Years of Experience'].astype(str).str.replace("ears", "")


In [71]:
dataset['Years of Experience'].unique()


array(['5.0', '3.0', '15.0', '7.0', '20.0', '2.0', '12.0', '4.0', '1.0',
       '10.0', '18.0', '6.0', '14.0', '16.0', '0.0', '22.0', '19.0',
       '9.0', '13.0', '11.0', '25.0', '21.0', '8.0', '17.0', '23.0',
       '24.0', '0.5', '1.5', '31.0', '30.0', '28.0', '33.0', '27.0',
       '34.0', '29.0', '26.0', '32.0'], dtype=object)

In [73]:
dataset['Years of Experience'] = dataset['Years of Experience'].astype(str).str.replace("ears", "")

In [74]:
dataset['Years of Experience'].unique()

array(['5.0', '3.0', '15.0', '7.0', '20.0', '2.0', '12.0', '4.0', '1.0',
       '10.0', '18.0', '6.0', '14.0', '16.0', '0.0', '22.0', '19.0',
       '9.0', '13.0', '11.0', '25.0', '21.0', '8.0', '17.0', '23.0',
       '24.0', '0.5', '1.5', '31.0', '30.0', '28.0', '33.0', '27.0',
       '34.0', '29.0', '26.0', '32.0'], dtype=object)

In [76]:
dataset['Years of Experience'] = dataset['Years of Experience'].str.replace("y", "")


In [77]:
dataset['Years of Experience'].unique()

array(['5.0', '3.0', '15.0', '7.0', '20.0', '2.0', '12.0', '4.0', '1.0',
       '10.0', '18.0', '6.0', '14.0', '16.0', '0.0', '22.0', '19.0',
       '9.0', '13.0', '11.0', '25.0', '21.0', '8.0', '17.0', '23.0',
       '24.0', '0.5', '1.5', '31.0', '30.0', '28.0', '33.0', '27.0',
       '34.0', '29.0', '26.0', '32.0'], dtype=object)

In [78]:
dataset.isna().sum()

Age                    0
Gender                 1
Education Level        2
Job Title              1
Years of Experience    0
Salary                 0
dtype: int64

In [79]:
dataset['Education Level'].unique()


array(["Bachelor's", "Master's", 'PhD', nan, "Bachelor's Degree",
       "Master's Degree", 'High School', 'phD'], dtype=object)

In [80]:
FinanceStatus_mode = dataset['Education Level'].mode()[0]
print(FinanceStatus_mode)


Bachelor's Degree


In [81]:
dataset['Education Level'].fillna(FinanceStatus_mode, inplace=True)


In [82]:
dataset['Education Level'].unique()

array(["Bachelor's", "Master's", 'PhD', "Bachelor's Degree",
       "Master's Degree", 'High School', 'phD'], dtype=object)